export const userConstant={
    REGISTER_REQUEST:'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS:'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE:'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST:'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS:'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE:'USERS_LOGIN_FAILURE',

    ORDER_APPROVAL_REQUEST:'USER_ORDER_APPROVAL_REQUEST',
    ORDER_APPROVAL_SUCCESS:'USER_ORDER_APPROVAL_SUCCESS',
    ORDER_APPROVAL_FAILURE:'USER_ORDER_APPROVAL_FAILURE',

    ORDER_REJECTION_REQUEST:'USER_ORDER_REJECTION_REQUEST',
    ORDER_REJECTION_SUCCESS:'USER_ORDER_REJECTION_SUCCESS',
    ORDER_REJECTION_FAILUER:'USER_ORDER_REJECTION_FAILUER',

    ANS_APPROVAL_REQUEST:'USERS_ANS_APPROVAL_REQUEST',
    ANS_APPROVAL_SUCCESS:'USERS_ANS_APPROVAL_SUCCESS',
    ANS_APPROVAL_FAILURE:'USERS_ANS_APPROVAL_FAILURE',

    ANS_REJECTION_REQUEST:'USERS_ANS_REJECTION_REQUEST',
    ANS_REJECTION_SUCCESS:'USERS_ANS_REJECTION_SUCCESS',
    ANS_REJECTION_FAILURE:'USERS_ANS_REJECTION_FAILURE'
    
}